// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz3K47X9G89iXhv7Vy3c67n3_LYCduDP8',
    appId: '1:863983236245:web:84e5161ea8f14eede9579c',
    messagingSenderId: '863983236245',
    projectId: 'flutter-chantier-app',
    authDomain: 'flutter-chantier-app.firebaseapp.com',
    storageBucket: 'flutter-chantier-app.firebasestorage.app',
    measurementId: 'G-GV262KTJN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk9zPWKbeB0Jq8vVr8OHK6v24oHlJOARU',
    appId: '1:863983236245:android:00732f0da495d15fe9579c',
    messagingSenderId: '863983236245',
    projectId: 'flutter-chantier-app',
    storageBucket: 'flutter-chantier-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbo3-DFXv4rgpr62pwVY5iQLBq1smX-Sc',
    appId: '1:863983236245:ios:f16f3e9bce9f4482e9579c',
    messagingSenderId: '863983236245',
    projectId: 'flutter-chantier-app',
    storageBucket: 'flutter-chantier-app.firebasestorage.app',
    iosBundleId: 'com.example.buildtrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbo3-DFXv4rgpr62pwVY5iQLBq1smX-Sc',
    appId: '1:863983236245:ios:f16f3e9bce9f4482e9579c',
    messagingSenderId: '863983236245',
    projectId: 'flutter-chantier-app',
    storageBucket: 'flutter-chantier-app.firebasestorage.app',
    iosBundleId: 'com.example.buildtrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz3K47X9G89iXhv7Vy3c67n3_LYCduDP8',
    appId: '1:863983236245:web:681959392fb58e92e9579c',
    messagingSenderId: '863983236245',
    projectId: 'flutter-chantier-app',
    authDomain: 'flutter-chantier-app.firebaseapp.com',
    storageBucket: 'flutter-chantier-app.firebasestorage.app',
    measurementId: 'G-5GCDE78PKL',
  );
}
